version: "3"
services:
  salad:
    image: "ghcr.io/ovyerus/saladbot"
    depends_on:
      salad_psql:
        condition: service_healthy
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      SALAD_DB_HOST: "salad_psql"
  salad_psql:
    image: "postgres:13-alpine"
    restart: "unless-stopped"
    env_file: ".env"
    volumes:
      - "salad_psql:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: "5s"
      timeout: "5s"
      retries: 5

volumes:
  salad_psql:
