name: Test and build
on: [push]

jobs:
  docker:
    name: Build Docker container and push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag name
        id: tag
        run:
          'echo "::set-output name=tag::${{ github.ref_name == ''master'' &&
          ''latest'' || github.ref_name }}"'

      - name: Build & push container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/ovyerus/saladbot:${{ steps.tag.outputs.tag }}
