name: Test and build
on: [push]

jobs:
  docker:
    name: Build Docker container and push to registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: nix build .#docker
      - run: nix flake check

      - name: Log into ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag name
        id: tag
        run:
          'echo "::set-output name=tag::${{ github.ref_name == ''master'' &&
          ''latest'' || github.ref_name }}"'

      - name: Push Docker image
        run: |
          docker load < result
          docker push ghcr.io/ovyerus/saladbot:${{ steps.tag.outputs.tag }}
